【WIP】Opus support
erikas-taroza/simple_audio pull request #29
Opened 2023-05-27 13:44 UTC by Yesterday17

Basic support for opus format. Fixes #5

## Tested platforms
- [ ] Windows
- [x] Linux
- [ ] macOS
- [ ] Android
- [ ] iOS

2023-05-27 15:35 UTC, erikas-taroza commented
Hello @Yesterday17 

Thank you for your contribution. I will take a look at it later today.

2023-05-29 02:31 UTC, erikas-taroza commented
Hello.

I tested on the `aarch64-linux-android` target and playback worked fine.

> OPUS files can not loop. Fixed in https://github.com/pdeljanov/Symphonia/pull/208. Cherry-picking might be necessary.

This can be cherry picked if it is not merged :)

2023-07-01 09:00 UTC, Yesterday17 commented
All CI has passed, marking as ready for review.

2023-07-01 17:56 UTC, erikas-taroza commented
> All CI has passed, marking as ready for review.

Great! I will cherry pick the `symphonia` PR you linked above and review the changes.

2023-07-01 18:18 UTC, erikas-taroza requested changes

2023-07-01 18:18 UTC, erikas-taroza commented on rust/Cargo.toml
> +symphonia = { git = "https://github.com/erikas-taroza/Symphonia", branch = "mp4-improvements", features = ["all"] }
Use the [`mp4-opus-improvements`](https://github.com/erikas-taroza/Symphonia/tree/mp4-opus-improvements) branch for Symphonia dependencies.

2023-07-01 18:18 UTC, erikas-taroza commented on rust/src/audio/opus.rs
> +const AUDIO_FRAME_RATE: usize = 1000 / 20; // FIXME: this value might be incorrect. We need to parse it from opus TOC.
Did you forget about this fixme?

2023-07-02 02:29 UTC, Yesterday17 commented
You may also fork https://github.com/ProjectAnni/audiopus_sys and change the patch in `Cargo.toml` into your fork. :eyes:

2023-07-02 02:31 UTC, Yesterday17 commented
Update: Androi CI is shown as passing but actually failed. I'm investigating the reason.

2023-07-02 02:52 UTC, erikas-taroza commented
Thanks for the changes!

> You may also fork https://github.com/ProjectAnni/audiopus_sys and change the patch in `Cargo.toml` into your fork. 👀

Good idea, will do that.

> Update: Androi CI is shown as passing but actually failed. I'm investigating the reason.

I need to fix that issue, caught me as well.

2023-07-02 02:54 UTC, erikas-taroza requested changes

2023-07-02 02:54 UTC, erikas-taroza commented on rust/Cargo.toml
> +audiopus_sys = { git = "https://github.com/ProjectAnni/audiopus_sys" }
Use this fork as discussed earlier: https://github.com/erikas-taroza/audiopus_sys

2023-07-02 11:28 UTC, Yesterday17 commented
> I need to fix that issue, caught me as well.

I've resolved this issue in https://github.com/ProjectAnni/audiopus_sys/commit/80542b524ecee73bc352c843358519186951cf0a . It compiles on my machine. CI is still running to validate whether it works with GitHub Actions.

2023-07-02 19:15 UTC, erikas-taroza commented
> > I need to fix that issue, caught me as well.
> 
> I've resolved this issue in [ProjectAnni/audiopus_sys@80542b5](https://github.com/ProjectAnni/audiopus_sys/commit/80542b524ecee73bc352c843358519186951cf0a) . It compiles on my machine. CI is still running to validate whether it works with GitHub Actions.

Looks like it worked :) I synced my fork with yours if you want to update the patch in `Cargo.toml`.

2023-07-03 03:15 UTC, erikas-taroza approved these changes
I appreciate the contribution :). LGTM

2023-07-03 03:15 UTC, merged